// <auto-generated />
using System;
using Domain.Database;
using Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250911143244_AddedRowInTaskTableIsGitHubIntegration")]
    partial class AddedRowInTaskTableIsGitHubIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Database.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<DateTime?>("Birthday")
                    .HasColumnType("datetime2");

                b.Property<string>("CardNumber")
                    .HasMaxLength(16)
                    .HasColumnType("nvarchar(16)");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Culture")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<bool>("IsNewUser")
                    .HasColumnType("bit");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("OrganizationCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<DateTime?>("RegistrationDate")
                    .HasColumnType("datetime2");

                b.Property<int?>("RewardLevel")
                    .HasColumnType("int");

                b.Property<int>("RoleInOrganization")
                    .HasColumnType("int");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Surname")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TelegramChatId")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TelegramTicket")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TelegramUserName")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex")
                    .HasFilter("[NormalizedUserName] IS NOT NULL");

                b.ToTable("AspNetUsers", (string)null);
            });

            modelBuilder.Entity("Domain.Database.GumroadWebhookLog", b =>
            {
                b.Property<string>("EventId")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("EventType")
                    .HasColumnType("int");

                b.Property<Guid?>("OrganizationCode")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("ProcessedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("SaleId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("SubscriptionId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("EventId");

                b.HasIndex("EventType");

                b.HasIndex("SaleId");

                b.HasIndex("SubscriptionId");

                b.ToTable("GumroadWebhookLog", (string)null);
            });

            modelBuilder.Entity("Domain.Database.Membership", b =>
            {
                b.Property<Guid>("MembershipId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("TeamId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("MembershipId");

                b.ToTable("Membership", (string)null);
            });

            modelBuilder.Entity("Domain.Database.Model.Notification", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("Created")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsReviewed")
                    .HasColumnType("bit");

                b.Property<string>("Title")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Notification", (string)null);
            });

            modelBuilder.Entity("Domain.Database.Model.ProjectUserPermission", b =>
            {
                b.Property<Guid>("ProjectId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<bool>("CanAssignUsers")
                    .HasColumnType("bit");

                b.Property<bool>("CanCreateTask")
                    .HasColumnType("bit");

                b.Property<bool>("CanDeleteTask")
                    .HasColumnType("bit");

                b.Property<bool>("CanEditTask")
                    .HasColumnType("bit");

                b.HasKey("ProjectId", "UserId");

                b.HasIndex("UserId");

                b.ToTable("ProjectUserPermission", (string)null);
            });

            modelBuilder.Entity("Domain.Database.Model.TariffPlan", b =>
            {
                b.Property<string>("Code")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasColumnName("Code");

                b.Property<int>("CountRequests")
                    .HasColumnType("int");

                b.Property<bool>("HasPriorityRequestsProcess")
                    .HasColumnType("bit");

                b.Property<bool>("HasProjectAccessControl")
                    .HasColumnType("bit");

                b.Property<bool>("HasTelegramIntegration")
                    .HasColumnType("bit");

                b.Property<long>("MaxStorageBytes")
                    .HasColumnType("bigint");

                b.Property<int>("MaxUsers")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("PriceMonth")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("PriceWithDiscount")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Code");

                b.ToTable("TariffPlan", (string)null);
            });

            modelBuilder.Entity("Domain.Database.Model.TariffPlanHistory", b =>
            {
                b.Property<Guid>("OrganizationCode")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("TariffPlanCode")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("DateFrom")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("DateTo")
                    .HasColumnType("datetime2");

                b.Property<string>("SubscriptionCode")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("OrganizationCode", "TariffPlanCode", "DateFrom");

                b.HasIndex("TariffPlanCode");

                b.ToTable("TariffPlanHistory", (string)null);
            });

            modelBuilder.Entity("Domain.Database.Organization", b =>
            {
                b.Property<Guid>("OrganizationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<long?>("GitHubInstallationId")
                    .HasColumnType("bigint");

                b.Property<bool?>("LockoutEnabled")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValueSql("(CONVERT([bit],(0)))");

                b.Property<DateTime?>("LockoutEnd")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Picture")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("RegistrationDate")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("('0001-01-01T00:00:00.0000000')");

                b.Property<long>("UsedStorageSpace")
                    .HasColumnType("bigint");

                b.HasKey("OrganizationId");

                b.ToTable("Organization", (string)null);
            });

            modelBuilder.Entity("Domain.Database.OrganizationAppeal", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("ID");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DescriptionRejecting")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("OrganizationCode")
                    .HasMaxLength(50)
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("OrganizationCode");

                b.ToTable("OrganizationAppeal", (string)null);
            });

            modelBuilder.Entity("Domain.Database.OrganizationFiles", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<byte[]>("Content")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<string>("ContentType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("DateUploaded")
                    .HasColumnType("datetime2");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("OrganizationCode")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uniqueidentifier");

                b.Property<long>("Size")
                    .HasColumnType("bigint");

                b.Property<Guid?>("TaskId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("OrganizationCode");

                b.HasIndex("ProjectId");

                b.HasIndex("TaskId");

                b.ToTable("OrganizationFiles", (string)null);
            });

            modelBuilder.Entity("Domain.Database.PersonalNote", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Text")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("PersonalNote", (string)null);
            });

            modelBuilder.Entity("Domain.Database.PersonalTodo", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("PersonalTodo", (string)null);
            });

            modelBuilder.Entity("Domain.Database.PersonalTodoTask", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDone")
                    .HasColumnType("bit");

                b.Property<int>("SortOrder")
                    .HasColumnType("int");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<Guid>("TodoId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("TodoId");

                b.ToTable("PersonalTodoTask", (string)null);
            });

            modelBuilder.Entity("Domain.Database.Project", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("ID");

                b.Property<string>("Client")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("DateAdd")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DateEdit")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("EndDate")
                    .HasColumnType("date");

                b.Property<string>("File")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("FIle");

                b.Property<string>("GitHubOwner")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("GitHubRepoName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ManagerId")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("ManagerID");

                b.Property<string>("OrganizationCode")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("nvarchar(max)")
                    .HasDefaultValueSql("(N'')");

                b.Property<int?>("Priority")
                    .HasColumnType("int");

                b.Property<string>("ShortDescription")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime?>("StartDate")
                    .HasColumnType("date");

                b.Property<int?>("Status")
                    .HasColumnType("int");

                b.Property<Guid?>("TeamId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(28)
                    .HasColumnType("nvarchar(28)");

                b.HasKey("Id");

                b.ToTable("Project", (string)null);
            });

            modelBuilder.Entity("Domain.Database.Task", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("ID");

                b.Property<int?>("ActualHours")
                    .HasColumnType("int");

                b.Property<int?>("ActualMinutes")
                    .HasColumnType("int");

                b.Property<string>("AssigneeId")
                    .HasMaxLength(450)
                    .HasColumnType("nvarchar(450)")
                    .HasColumnName("AssigneeID");

                b.Property<int>("Complexity")
                    .HasColumnType("int");

                b.Property<DateTime?>("ComplitedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedByUserId")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("DateAdd")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("DateEdit")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("EndDate")
                    .HasColumnType("datetime");

                b.Property<string>("GitHubBranch")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("GitHubIssueNumber")
                    .HasColumnType("int");

                b.Property<string>("GitHubOwner")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("GitHubRepoName")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool?>("IsAgreedOverdue")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValueSql("(CONVERT([bit],(0)))");

                b.Property<bool>("IsGitHubIntegration")
                    .HasColumnType("bit");

                b.Property<string>("OrganizationCode")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("nvarchar(450)")
                    .HasDefaultValueSql("(N'')");

                b.Property<string>("PerformanceNote")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Priority")
                    .HasColumnType("int");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("ProjectID");

                b.Property<DateTime?>("ReviewDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("StartDate")
                    .HasColumnType("datetime");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.HasKey("Id");

                b.HasIndex(new[] { "AssigneeId", "Status", "OrganizationCode" }, "IX_Tasks_Assignee_Status_Organization");

                b.HasIndex(new[] { "ProjectId" }, "IX_Tasks_ProjectId");

                b.ToTable("Task", (string)null);
            });

            modelBuilder.Entity("Domain.Database.TaskProgressDto", b =>
            {
                b.Property<int>("CompletedTasks")
                    .HasColumnType("int");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("TotalTasks")
                    .HasColumnType("int");

                b.ToTable("TaskProgressDto");
            });

            modelBuilder.Entity("Domain.Database.TasksCountByUser", b =>
            {
                b.Property<int>("SumCountTask")
                    .HasColumnType("int");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.ToTable("TasksCountByUser");
            });

            modelBuilder.Entity("Domain.Database.Team", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("(newid())");

                b.Property<string>("Name")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("OrganizationCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Team", (string)null);
            });

            modelBuilder.Entity("TaskJect.Web.Models.TasksStatisticByPeriod", b =>
            {
                b.Property<int>("SumCountTask")
                    .HasColumnType("int");

                b.Property<int>("SumHours")
                    .HasColumnType("int");

                b.Property<int>("SumMinutes")
                    .HasColumnType("int");

                b.Property<int>("SumPoints")
                    .HasColumnType("int");

                b.Property<int>("SumTaskOverdue")
                    .HasColumnType("int");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.ToTable("TasksStatisticByPeriod");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex")
                    .HasFilter("[NormalizedName] IS NOT NULL");

                b.ToTable("AspNetRoles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ClaimValue")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderKey")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("RoleId")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("LoginProvider")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("Value")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens", (string)null);
            });

            modelBuilder.Entity("Domain.Database.Model.Notification", b =>
            {
                b.HasOne("Domain.Database.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("Domain.Database.Model.ProjectUserPermission", b =>
            {
                b.HasOne("Domain.Database.Project", null)
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Domain.Database.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Domain.Database.Model.TariffPlanHistory", b =>
            {
                b.HasOne("Domain.Database.Organization", null)
                    .WithMany()
                    .HasForeignKey("OrganizationCode")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Domain.Database.Model.TariffPlan", null)
                    .WithMany()
                    .HasForeignKey("TariffPlanCode")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("Domain.Database.OrganizationAppeal", b =>
            {
                b.HasOne("Domain.Database.Organization", null)
                    .WithMany()
                    .HasForeignKey("OrganizationCode")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("FK_OrganizationAppeal_Organization");
            });

            modelBuilder.Entity("Domain.Database.OrganizationFiles", b =>
            {
                b.HasOne("Domain.Database.Organization", null)
                    .WithMany()
                    .HasForeignKey("OrganizationCode")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Domain.Database.Project", null)
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("Domain.Database.Task", null)
                    .WithMany()
                    .HasForeignKey("TaskId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("Domain.Database.PersonalNote", b =>
            {
                b.HasOne("Domain.Database.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("Domain.Database.PersonalTodo", b =>
            {
                b.HasOne("Domain.Database.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("Domain.Database.PersonalTodoTask", b =>
            {
                b.HasOne("Domain.Database.PersonalTodo", "Todo")
                    .WithMany("Tasks")
                    .HasForeignKey("TodoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Todo");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("Domain.Database.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("Domain.Database.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Domain.Database.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("Domain.Database.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Domain.Database.PersonalTodo", b =>
            {
                b.Navigation("Tasks");
            });
#pragma warning restore 612, 618
        }
    }
}