//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskJect.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskJect.Web.Resources.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be filled in..
        /// </summary>
        public static string AllFieldsMustFilled {
            get {
                return ResourceManager.GetString("AllFieldsMustFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of memberships could not be retrieved. Please try again later or contact support..
        /// </summary>
        public static string allMembershipsLoadErrorMessage {
            get {
                return ResourceManager.GetString("allMembershipsLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load memberships.
        /// </summary>
        public static string allMembershipsLoadErrorTitle {
            get {
                return ResourceManager.GetString("allMembershipsLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while linking an account..
        /// </summary>
        public static string AnUnknownErrorOccurredWhileLinkingAccount {
            get {
                return ResourceManager.GetString("AnUnknownErrorOccurredWhileLinkingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to archive completed tasks..
        /// </summary>
        public static string ArchiveCompletedFailed {
            get {
                return ResourceManager.GetString("ArchiveCompletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ComparePasswordError {
            get {
                return ResourceManager.GetString("ComparePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict while saving data. Please try again..
        /// </summary>
        public static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new organization and new user with email is successful!.
        /// </summary>
        public static string CreateNewOrganizationUserSuccessful {
            get {
                return ResourceManager.GetString("CreateNewOrganizationUserSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user with email is successful!.
        /// </summary>
        public static string CreateNewUserWithEmailSuccessful {
            get {
                return ResourceManager.GetString("CreateNewUserWithEmailSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user with email was not successful!.
        /// </summary>
        public static string CreateNewUserWithEmailWasNotSuccessful {
            get {
                return ResourceManager.GetString("CreateNewUserWithEmailWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create organization was not successful!.
        /// </summary>
        public static string CreateOrganizationWasNotSuccessful {
            get {
                return ResourceManager.GetString("CreateOrganizationWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create organization was not successful! The organization already exists!.
        /// </summary>
        public static string CreateOrganizationWasSuccessfulAlreadyExists {
            get {
                return ResourceManager.GetString("CreateOrganizationWasSuccessfulAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new organization was successful! Creating new user failed!.
        /// </summary>
        public static string CreatingNewOrganizationUserWasSuccessful {
            get {
                return ResourceManager.GetString("CreatingNewOrganizationUserWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new organization was successful! Creating a package plan failed!.
        /// </summary>
        public static string CreatingNewOrganizationWasSuccessful {
            get {
                return ResourceManager.GetString("CreatingNewOrganizationWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tariff successfully changed!.
        /// </summary>
        public static string CurrentTariffChanged {
            get {
                return ResourceManager.GetString("CurrentTariffChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tariff is the same.
        /// </summary>
        public static string CurrentTariffSame {
            get {
                return ResourceManager.GetString("CurrentTariffSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data in organization was not successful!.
        /// </summary>
        public static string DeleteDataOrganizationWasNotSuccessful {
            get {
                return ResourceManager.GetString("DeleteDataOrganizationWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete organization appeal is successful!.
        /// </summary>
        public static string DeleteOrganizationAppealSuccessful {
            get {
                return ResourceManager.GetString("DeleteOrganizationAppealSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete organization appeal was not successful!.
        /// </summary>
        public static string DeleteOrganizationAppealWasNotSuccessful {
            get {
                return ResourceManager.GetString("DeleteOrganizationAppealWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete organization is successful!.
        /// </summary>
        public static string DeleteOrganizationSuccessful {
            get {
                return ResourceManager.GetString("DeleteOrganizationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete organization was not successful!.
        /// </summary>
        public static string DeleteOrganizationWasNotSuccessful {
            get {
                return ResourceManager.GetString("DeleteOrganizationWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user is successful!.
        /// </summary>
        public static string DeleteUserSuccessful {
            get {
                return ResourceManager.GetString("DeleteUserSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user was not successful!.
        /// </summary>
        public static string DeleteUserWasNotSuccessful {
            get {
                return ResourceManager.GetString("DeleteUserWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is already in use..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role name &apos;{0}&apos; is already in use..
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &apos;{0}&apos; is already in use..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he {0} field is not a valid e-mail address..
        /// </summary>
        public static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and Code must be provided.
        /// </summary>
        public static string EmailCodeProvided {
            get {
                return ResourceManager.GetString("EmailCodeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Email confirmation failed..
        /// </summary>
        public static string EmailConfirmationFailed {
            get {
                return ResourceManager.GetString("EmailConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed successfully..
        /// </summary>
        public static string EmailConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To log in, first confirm your email..
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! We encountered a problem while calculating analytics. Please try again later or contact the administration.
        /// </summary>
        public static string ErrorCalculatingAnalyticsMessage {
            get {
                return ResourceManager.GetString("ErrorCalculatingAnalyticsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error unlinking repository..
        /// </summary>
        public static string ErrorUnlinkingRepository {
            get {
                return ResourceManager.GetString("ErrorUnlinkingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating the role in the organization!.
        /// </summary>
        public static string ErrorUpdatingRoleOrganization {
            get {
                return ResourceManager.GetString("ErrorUpdatingRoleOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete file..
        /// </summary>
        public static string FailedToDeleteFile {
            get {
                return ResourceManager.GetString("FailedToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File deleted successfully..
        /// </summary>
        public static string FileDeletedSuccessfully {
            get {
                return ResourceManager.GetString("FileDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is missing or empty.
        /// </summary>
        public static string FileMissingOrEmpty {
            get {
                return ResourceManager.GetString("FileMissingOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully.
        /// </summary>
        public static string FileSavedSuccessfully {
            get {
                return ResourceManager.GetString("FileSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file..
        /// </summary>
        public static string FileSaveFailed {
            get {
                return ResourceManager.GetString("FileSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload file.
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully.
        /// </summary>
        public static string FileUploadSuccess {
            get {
                return ResourceManager.GetString("FileUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub has not removed the app.
        /// </summary>
        public static string GitHubNotDeleteApp {
            get {
                return ResourceManager.GetString("GitHubNotDeleteApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub is not linked.
        /// </summary>
        public static string GitHubNotLinked {
            get {
                return ResourceManager.GetString("GitHubNotLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id organization is empty!.
        /// </summary>
        public static string IdOrganizationEmpty {
            get {
                return ResourceManager.GetString("IdOrganizationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id organization equals null!.
        /// </summary>
        public static string IdOrganizationEqualsNull {
            get {
                return ResourceManager.GetString("IdOrganizationEqualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id project equals null!.
        /// </summary>
        public static string IdProjectEqualsNull {
            get {
                return ResourceManager.GetString("IdProjectEqualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id task equals null!.
        /// </summary>
        public static string IdTaskEqualsNull {
            get {
                return ResourceManager.GetString("IdTaskEqualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id team equals null!.
        /// </summary>
        public static string IdTeamEqualsNull {
            get {
                return ResourceManager.GetString("IdTeamEqualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id team or id user equals null!.
        /// </summary>
        public static string IdTeamIdUserEqualsNull {
            get {
                return ResourceManager.GetString("IdTeamIdUserEqualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id user equals null!.
        /// </summary>
        public static string IdUserEqualsNull {
            get {
                return ResourceManager.GetString("IdUserEqualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id user or role equals null!.
        /// </summary>
        public static string IdUserRoleEqualsNull {
            get {
                return ResourceManager.GetString("IdUserRoleEqualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid model or null model!.
        /// </summary>
        public static string InvalidModelNullModel {
            get {
                return ResourceManager.GetString("InvalidModelNullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout user is successful!.
        /// </summary>
        public static string LockoutUserSuccessful {
            get {
                return ResourceManager.GetString("LockoutUserSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout user was not successful!.
        /// </summary>
        public static string LockoutUserWasNotSuccessful {
            get {
                return ResourceManager.GetString("LockoutUserWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login is already linked to another account..
        /// </summary>
        public static string LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t retrieve the user&apos;s memberships. Please try again later or contact support if the issue persists..
        /// </summary>
        public static string membershipsByUserLoadErrorMessage {
            get {
                return ResourceManager.GetString("membershipsByUserLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load user memberships.
        /// </summary>
        public static string membershipsByUserLoadErrorTitle {
            get {
                return ResourceManager.GetString("membershipsByUserLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing project ID.
        /// </summary>
        public static string MissingProjectId {
            get {
                return ResourceManager.GetString("MissingProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model project equals null!.
        /// </summary>
        public static string ModelProjectEqualsNull {
            get {
                return ResourceManager.GetString("ModelProjectEqualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to export.
        /// </summary>
        public static string NoDataToExport {
            get {
                return ResourceManager.GetString("NoDataToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find details for the current user. Please try again later or contact the administration.
        /// </summary>
        public static string NoFoundCurrentUser {
            get {
                return ResourceManager.GetString("NoFoundCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No found details.
        /// </summary>
        public static string NoFoundDetails {
            get {
                return ResourceManager.GetString("NoFoundDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find users for your organization, try again or contact administrator.
        /// </summary>
        public static string NoFoundUsersMessage {
            get {
                return ResourceManager.GetString("NoFoundUsersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No found users.
        /// </summary>
        public static string NoFoundUsersTitle {
            get {
                return ResourceManager.GetString("NoFoundUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find information about available tariff plans..
        /// </summary>
        public static string NoInfoAboutTariffPlans {
            get {
                return ResourceManager.GetString("NoInfoAboutTariffPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repository selected.
        /// </summary>
        public static string NoRepositorySelected {
            get {
                return ResourceManager.GetString("NoRepositorySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization appeal edit is successful!.
        /// </summary>
        public static string OrganizationAppealEditSuccessful {
            get {
                return ResourceManager.GetString("OrganizationAppealEditSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization appeal edit was not successful!.
        /// </summary>
        public static string OrganizationAppealEditWasNotSuccessful {
            get {
                return ResourceManager.GetString("OrganizationAppealEditWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization appeal equals null!.
        /// </summary>
        public static string OrganizationAppealEqualsNull {
            get {
                return ResourceManager.GetString("OrganizationAppealEqualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to show.
        /// </summary>
        public static string organizationAppealsLoadErrorMessage {
            get {
                return ResourceManager.GetString("organizationAppealsLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improvements not found.
        /// </summary>
        public static string organizationAppealsLoadErrorTitle {
            get {
                return ResourceManager.GetString("organizationAppealsLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected organization not found. Please try again later or contact the administration.
        /// </summary>
        public static string organizationLoadErrorMessage {
            get {
                return ResourceManager.GetString("organizationLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization not found.
        /// </summary>
        public static string organizationLoadErrorTitle {
            get {
                return ResourceManager.GetString("organizationLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization is lockout, Users is not lockout.
        /// </summary>
        public static string OrganizationLockoutUsersNotLockout {
            get {
                return ResourceManager.GetString("OrganizationLockoutUsersNotLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization not found!.
        /// </summary>
        public static string OrganizationNotFound {
            get {
                return ResourceManager.GetString("OrganizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find organizations. Please try again later or contact the administration.
        /// </summary>
        public static string organizationsLoadErrorMessage {
            get {
                return ResourceManager.GetString("organizationsLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No found organizations.
        /// </summary>
        public static string organizationsLoadErrorTitle {
            get {
                return ResourceManager.GetString("organizationsLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find organizations details. Please try again later or contact the administration.
        /// </summary>
        public static string organizationsLoadUserInfoErrorMessage {
            get {
                return ResourceManager.GetString("organizationsLoadUserInfoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No found organization info.
        /// </summary>
        public static string organizationsUserInfoLoadErrorTitle {
            get {
                return ResourceManager.GetString("organizationsUserInfoLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization is unlocked, Users is not unlocked.
        /// </summary>
        public static string OrganizationUnlockedUsersNotUnlocked {
            get {
                return ResourceManager.GetString("OrganizationUnlockedUsersNotUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system was unable to retrieve overdue task details. Please try again later or contact support..
        /// </summary>
        public static string overdueTasksLoadErrorMessage {
            get {
                return ResourceManager.GetString("overdueTasksLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download overdue tasks.
        /// </summary>
        public static string overdueTasksLoadErrorTitle {
            get {
                return ResourceManager.GetString("overdueTasksLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one digit..
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one lowercase letter..
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one special character..
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain at least one uppercase letter..
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least {0} characters long..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no repository associated with this project..
        /// </summary>
        public static string ProjectHasNoLinkedRepository {
            get {
                return ResourceManager.GetString("ProjectHasNoLinkedRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found.
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested project could not be found. It might have been removed or the identifier is incorrect..
        /// </summary>
        public static string projectOverviewLoadErrorMessage {
            get {
                return ResourceManager.GetString("projectOverviewLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project information not available.
        /// </summary>
        public static string projectOverviewLoadErrorTitle {
            get {
                return ResourceManager.GetString("projectOverviewLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects related to the selected organization are currently unavailable. Please try again later..
        /// </summary>
        public static string projectsByOrganizationLoadErrorMessage {
            get {
                return ResourceManager.GetString("projectsByOrganizationLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load projects.
        /// </summary>
        public static string projectsByOrganizationLoadErrorTitle {
            get {
                return ResourceManager.GetString("projectsByOrganizationLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system could not find any projects for your organization. Please check your access rights or contact your administrator..
        /// </summary>
        public static string projectsLoadErrorMessage {
            get {
                return ResourceManager.GetString("projectsLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load project list.
        /// </summary>
        public static string projectsLoadErrorTitle {
            get {
                return ResourceManager.GetString("projectsLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}..
        /// </summary>
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not valid..
        /// </summary>
        public static string RegularExpressionAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles not found. Please try again later or contact administration..
        /// </summary>
        public static string rolesLoadErrorMessage {
            get {
                return ResourceManager.GetString("rolesLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles not found.
        /// </summary>
        public static string rolesLoadErrorTitle {
            get {
                return ResourceManager.GetString("rolesLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role update is successful!.
        /// </summary>
        public static string RoleUpdateSuccessful {
            get {
                return ResourceManager.GetString("RoleUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role update was not successful!.
        /// </summary>
        public static string RoleUpdateWasNotSuccessful {
            get {
                return ResourceManager.GetString("RoleUpdateWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again later or contact the support..
        /// </summary>
        public static string SERVER_ERROR {
            get {
                return ResourceManager.GetString("SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t load the information about this task. It might have been deleted or is temporarily inaccessible..
        /// </summary>
        public static string singleTaskLoadErrorMessage {
            get {
                return ResourceManager.GetString("singleTaskLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task details unavailable.
        /// </summary>
        public static string singleTaskLoadErrorTitle {
            get {
                return ResourceManager.GetString("singleTaskLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage of your organization is full. Please delete some data or change your tariff plan..
        /// </summary>
        public static string StorageYourOrganizationFull {
            get {
                return ResourceManager.GetString("StorageYourOrganizationFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}..
        /// </summary>
        public static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change the user role..
        /// </summary>
        public static string SwitchRoleWasNotSuccessful {
            get {
                return ResourceManager.GetString("SwitchRoleWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff plan is not updated.
        /// </summary>
        public static string TariffPlanNotUpdated {
            get {
                return ResourceManager.GetString("TariffPlanNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff plan updated.
        /// </summary>
        public static string TariffPlanUpdated {
            get {
                return ResourceManager.GetString("TariffPlanUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve task details for the selected period. Please try again or report a problem..
        /// </summary>
        public static string taskDetailsLoadErrorMessage {
            get {
                return ResourceManager.GetString("taskDetailsLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load task details.
        /// </summary>
        public static string taskDetailsLoadErrorTitle {
            get {
                return ResourceManager.GetString("taskDetailsLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task id or hours and minutes, is null!.
        /// </summary>
        public static string TaskIdHoursMinutesNull {
            get {
                return ResourceManager.GetString("TaskIdHoursMinutesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task model equals null!.
        /// </summary>
        public static string TaskModelEqualsNull {
            get {
                return ResourceManager.GetString("TaskModelEqualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn’t get the list of tasks for the selected user. Please refresh the page or try again later..
        /// </summary>
        public static string tasksByUserLoadErrorMessage {
            get {
                return ResourceManager.GetString("tasksByUserLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load tasks.
        /// </summary>
        public static string tasksByUserLoadErrorTitle {
            get {
                return ResourceManager.GetString("tasksByUserLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task successfully changed.
        /// </summary>
        public static string TaskSuccessfullyChanged {
            get {
                return ResourceManager.GetString("TaskSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task successfully created.
        /// </summary>
        public static string TaskSuccessfullyCreated {
            get {
                return ResourceManager.GetString("TaskSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team or members is null!.
        /// </summary>
        public static string TeamMembersNull {
            get {
                return ResourceManager.GetString("TeamMembersNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team model equals null!.
        /// </summary>
        public static string TeamModelQualsNull {
            get {
                return ResourceManager.GetString("TeamModelQualsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name update was not successful!.
        /// </summary>
        public static string TeamNameUpdateWasNotSuccessful {
            get {
                return ResourceManager.GetString("TeamNameUpdateWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team not found!.
        /// </summary>
        public static string TeamNotFound {
            get {
                return ResourceManager.GetString("TeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to find information about the team assigned to this project. Try again later..
        /// </summary>
        public static string teamOverviewLoadErrorMessage {
            get {
                return ResourceManager.GetString("teamOverviewLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team information not available.
        /// </summary>
        public static string teamOverviewLoadErrorTitle {
            get {
                return ResourceManager.GetString("teamOverviewLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn’t retrieve teams for the selected organization. Please refresh or try again later..
        /// </summary>
        public static string teamsByOrganizationLoadErrorMessage {
            get {
                return ResourceManager.GetString("teamsByOrganizationLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load teams.
        /// </summary>
        public static string teamsByOrganizationLoadErrorTitle {
            get {
                return ResourceManager.GetString("teamsByOrganizationLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your request, we will review it shortly and provide feedback!.
        /// </summary>
        public static string ThankYouForYourRequestReview {
            get {
                return ResourceManager.GetString("ThankYouForYourRequestReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The letter was sent successfully..
        /// </summary>
        public static string TheLetterWasSentSuccessfully {
            get {
                return ResourceManager.GetString("TheLetterWasSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no organization with this Id!.
        /// </summary>
        public static string ThereOrganizationThisId {
            get {
                return ResourceManager.GetString("ThereOrganizationThisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role in the organization has been successfully updated!.
        /// </summary>
        public static string TheRoleOrganizationSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("TheRoleOrganizationSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team is being used in the following projects.
        /// </summary>
        public static string TheTeamBeingUsedFollowingProjects {
            get {
                return ResourceManager.GetString("TheTeamBeingUsedFollowingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This members are already in team!.
        /// </summary>
        public static string ThisMembersAlreadyTeam {
            get {
                return ResourceManager.GetString("ThisMembersAlreadyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve score statistics. Please refresh the page or contact support..
        /// </summary>
        public static string totalPointsStatsLoadErrorMessage {
            get {
                return ResourceManager.GetString("totalPointsStatsLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to calculate points.
        /// </summary>
        public static string totalPointsStatsLoadErrorTitle {
            get {
                return ResourceManager.GetString("totalPointsStatsLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve statistics on total number of tasks. Please try again or contact your administrator..
        /// </summary>
        public static string totalTasksStatsLoadErrorMessage {
            get {
                return ResourceManager.GetString("totalTasksStatsLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to calculate total tasks.
        /// </summary>
        public static string totalTasksStatsLoadErrorTitle {
            get {
                return ResourceManager.GetString("totalTasksStatsLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unconnect.
        /// </summary>
        public static string UnconnectFailed {
            get {
                return ResourceManager.GetString("UnconnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconnect is success!.
        /// </summary>
        public static string UnconnectSuccessful {
            get {
                return ResourceManager.GetString("UnconnectSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock user is successful!.
        /// </summary>
        public static string UnlockUserSuccessful {
            get {
                return ResourceManager.GetString("UnlockUserSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock user was not successful!.
        /// </summary>
        public static string UnlockUserWasNotSuccessful {
            get {
                return ResourceManager.GetString("UnlockUserWasNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already has a password..
        /// </summary>
        public static string UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already has the role &apos;{0}&apos;..
        /// </summary>
        public static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking is not allowed for this user..
        /// </summary>
        public static string UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have role &apos;{0}&apos;..
        /// </summary>
        public static string UserNotInRole {
            get {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the task list for the user. Please refresh the page or contact technical support..
        /// </summary>
        public static string userTasksLoadErrorMessage {
            get {
                return ResourceManager.GetString("userTasksLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load task list.
        /// </summary>
        public static string userTasksLoadErrorTitle {
            get {
                return ResourceManager.GetString("userTasksLoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update information about user. Please try again later or contact the administration.
        /// </summary>
        public static string userUpdateErrorMessage {
            get {
                return ResourceManager.GetString("userUpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user info failed.
        /// </summary>
        public static string userUpdateErrorTitle {
            get {
                return ResourceManager.GetString("userUpdateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email does not exist..
        /// </summary>
        public static string UserWithEmailNotExist {
            get {
                return ResourceManager.GetString("UserWithEmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your operation is successful!.
        /// </summary>
        public static string YourOperationSuccessful {
            get {
                return ResourceManager.GetString("YourOperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your operation was not successful!.
        /// </summary>
        public static string YourOperationWasNotSuccessful {
            get {
                return ResourceManager.GetString("YourOperationWasNotSuccessful", resourceCulture);
            }
        }
    }
}
