//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskJect.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LandingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LandingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskJect.Web.Resources.LandingResources", typeof(LandingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all the features are included.
        /// </summary>
        public static string allFeaturesIncluded {
            get {
                return ResourceManager.GetString("allFeaturesIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-in-one tool for advanced teamwork.
        /// </summary>
        public static string AllToolAdvancedTeamwork {
            get {
                return ResourceManager.GetString("AllToolAdvancedTeamwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze all the metrics to make data-driven decisions.
        /// </summary>
        public static string AnalyzeMetricsMake {
            get {
                return ResourceManager.GetString("AnalyzeMetricsMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign, track, and complete tasks efficiently.
        /// </summary>
        public static string AssignTrack {
            get {
                return ResourceManager.GetString("AssignTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the moment, we don&apos;t have any integrations with other services (for example, Jira, Trello, Notion)..
        /// </summary>
        public static string AtTheMoment {
            get {
                return ResourceManager.GetString("AtTheMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the moment, such cases are considered individually..
        /// </summary>
        public static string AtTheMomentSuchCases {
            get {
                return ResourceManager.GetString("AtTheMomentSuchCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking a user only restricts the participant&apos;s access to the service, and deleting it will lead to the loss of information about the task performer..
        /// </summary>
        public static string BlockingUserOnlyRestricts {
            get {
                return ResourceManager.GetString("BlockingUserOnlyRestricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build by developers for developers.
        /// </summary>
        public static string BuildByDevelopersForDevelopers {
            get {
                return ResourceManager.GetString("BuildByDevelopersForDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I integrate my tasks from other task accounting services into yours.
        /// </summary>
        public static string CanIntegrateTasksFrom {
            get {
                return ResourceManager.GetString("CanIntegrateTasksFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can one user with one account be a member of several organizations.
        /// </summary>
        public static string CanOneUserWith {
            get {
                return ResourceManager.GetString("CanOneUserWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out TaskJect’s features in our short demo.
        /// </summary>
        public static string CheckOutTaskJectsFeaturesShortDemo {
            get {
                return ResourceManager.GetString("CheckOutTaskJectsFeaturesShortDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborate seamlessly and streamline teamwork.
        /// </summary>
        public static string CollaborateSeamlessly {
            get {
                return ResourceManager.GetString("CollaborateSeamlessly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to find out the most suitable package for your team.
        /// </summary>
        public static string ContactFindMostSuitablePackage {
            get {
                return ResourceManager.GetString("ContactFindMostSuitablePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize your profile for the best experiences.
        /// </summary>
        public static string CustomizeProfile {
            get {
                return ResourceManager.GetString("CustomizeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed with precision.
        /// </summary>
        public static string DesignedPrecision {
            get {
                return ResourceManager.GetString("DesignedPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does every member of my team have to submit such an application.
        /// </summary>
        public static string DoesEveryMember {
            get {
                return ResourceManager.GetString("DoesEveryMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features Used in TaskJect.
        /// </summary>
        public static string FeaturesUsedTaskJect {
            get {
                return ResourceManager.GetString("FeaturesUsedTaskJect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Thank you for your interest in our service. We will process your request shortly and provide feedback.&lt;/p&gt;&lt;p&gt;Best regards,&lt;/p&gt;&lt;p&gt;The TaskJect Team&lt;/p&gt;.
        /// </summary>
        public static string FeedbackBodyForRequest {
            get {
                return ResourceManager.GetString("FeedbackBodyForRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ve Received Your Request.
        /// </summary>
        public static string FeedbackSubjectForRequest {
            get {
                return ResourceManager.GetString("FeedbackSubjectForRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEEDBACK.
        /// </summary>
        public static string FeedbackUpperCase {
            get {
                return ResourceManager.GetString("FeedbackUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for free and simplify your workflow!.
        /// </summary>
        public static string forFreeSimplify {
            get {
                return ResourceManager.GetString("forFreeSimplify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently asked questions.
        /// </summary>
        public static string FrequentlyAskedQuestions {
            get {
                return ResourceManager.GetString("FrequentlyAskedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From small teams to growing businesses, here’s what people say about working with TaskJect..
        /// </summary>
        public static string FromSmallTeamsToGrowingBusinesses {
            get {
                return ResourceManager.GetString("FromSmallTeamsToGrowingBusinesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain insights with detailed performance reports.
        /// </summary>
        public static string GainInsightsDetailed {
            get {
                return ResourceManager.GetString("GainInsightsDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I create a personal account.
        /// </summary>
        public static string HowCreatePersonalAccount {
            get {
                return ResourceManager.GetString("HowCreatePersonalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I add a new user.
        /// </summary>
        public static string HowDoAddNewUser {
            get {
                return ResourceManager.GetString("HowDoAddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do the roles in the organization and team work.
        /// </summary>
        public static string HowRolesOrganizationTeam {
            get {
                return ResourceManager.GetString("HowRolesOrganizationTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If I don&apos;t use your service for a while, what happens to my account.
        /// </summary>
        public static string IfIDontUseYourService {
            get {
                return ResourceManager.GetString("IfIDontUseYourService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the disk space limit is exceeded, creating and editing projects and tasks will become unavailable until you return to the limit..
        /// </summary>
        public static string IfTheDiskSpaceLimitExceeded {
            get {
                return ResourceManager.GetString("IfTheDiskSpaceLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *If the plan is not renewed within 3 months, all blocked users will be deleted, as well as some old tasks to free up space..
        /// </summary>
        public static string IfThePlanRenewedWithin {
            get {
                return ResourceManager.GetString("IfThePlanRenewedWithin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you exceed the user limit, newly registered users will be blocked..
        /// </summary>
        public static string IfYouExceedUserLimit {
            get {
                return ResourceManager.GetString("IfYouExceedUserLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you haven&apos;t exceeded the user and disk space limits for your basic plan, there will be no changes..
        /// </summary>
        public static string IfYouHaventExceeded {
            get {
                return ResourceManager.GetString("IfYouHaventExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you leave your profile inactive, we will contact you to clarify your intentions for using the application. We will keep your data for a year so that you do not lose important information..
        /// </summary>
        public static string IfYouLeaveYourProfileInactive {
            get {
                return ResourceManager.GetString("IfYouLeaveYourProfileInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Integration.
        /// </summary>
        public static string integrationWithTelegram {
            get {
                return ResourceManager.GetString("integrationWithTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the section “My organization” -&gt; “Upgrade Request”.
        /// </summary>
        public static string InTheSection {
            get {
                return ResourceManager.GetString("InTheSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it possible to change the tariff plan.
        /// </summary>
        public static string IsPossibleChangeTariff {
            get {
                return ResourceManager.GetString("IsPossibleChangeTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it possible to enter via Google/Microsoft.
        /// </summary>
        public static string IsPossibleEnterVia {
            get {
                return ResourceManager.GetString("IsPossibleEnterVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it possible to track the time spent on tasks.
        /// </summary>
        public static string IsPossibleTrack {
            get {
                return ResourceManager.GetString("IsPossibleTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the team leader submits the application. After approval by our moderators, the team leader will be able to invite members to join their team in their profile under the organization tab.
        /// </summary>
        public static string OnlyTheTeamLeader {
            get {
                return ResourceManager.GetString("OnlyTheTeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize your processes to ensure convenient work.
        /// </summary>
        public static string OptimizeProcessesEnsure {
            get {
                return ResourceManager.GetString("OptimizeProcessesEnsure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize projects with clear workflows and real-time updates.
        /// </summary>
        public static string OrganizeProjectsWorkflows {
            get {
                return ResourceManager.GetString("OrganizeProjectsWorkflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission consists of 4 major steps.
        /// </summary>
        public static string OurMissionConsistsSteps {
            get {
                return ResourceManager.GetString("OurMissionConsistsSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission is to make web design easy, so you can focus on building your brand.
        /// </summary>
        public static string OurMissionMakeWebDesign {
            get {
                return ResourceManager.GetString("OurMissionMakeWebDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our plans are very affordable and are suited for teams of various sizes. Even a basic plan makes a difference..
        /// </summary>
        public static string OurPlansAffordableMainlyPlaced {
            get {
                return ResourceManager.GetString("OurPlansAffordableMainlyPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for the entire organization.
        /// </summary>
        public static string PriceForEntireOrganization {
            get {
                return ResourceManager.GetString("PriceForEntireOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proven track record. Worldwide trust..
        /// </summary>
        public static string ProvenTrackRecordWorldwideTrust {
            get {
                return ResourceManager.GetString("ProvenTrackRecordWorldwideTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set goals and meet deadlines.
        /// </summary>
        public static string SetGoalsDeadlines {
            get {
                return ResourceManager.GetString("SetGoalsDeadlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple task tracking that lets you focus on shipping, not managing.
        /// </summary>
        public static string SimpleTaskTrackingNotManaging {
            get {
                return ResourceManager.GetString("SimpleTaskTrackingNotManaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the reviews our clients gave which brings motivation to work for future projects.
        /// </summary>
        public static string SomeReviewsClientsWhich {
            get {
                return ResourceManager.GetString("SomeReviewsClientsWhich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds like a good fit? Reach out to us.
        /// </summary>
        public static string SoundsLikeGoodFit {
            get {
                return ResourceManager.GetString("SoundsLikeGoodFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit an application.
        /// </summary>
        public static string submitApplication {
            get {
                return ResourceManager.GetString("submitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskJect comes with most affordable pricing range.
        /// </summary>
        public static string TaskJectComesAffordablePricing {
            get {
                return ResourceManager.GetString("TaskJectComesAffordablePricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskject comes with multiple customization options that are very easy to implement..
        /// </summary>
        public static string taskjectMultipleCustomization {
            get {
                return ResourceManager.GetString("taskjectMultipleCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission is to make teamwork easy. You can focus on your tasks, not the management..
        /// </summary>
        public static string TeamWorkEasyText {
            get {
                return ResourceManager.GetString("TeamWorkEasyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The head of the organization invites a new member to the available slots on the Teams tab, and the invited user will receive a corresponding email.
        /// </summary>
        public static string TheHeadOfTheOrganizationInvites {
            get {
                return ResourceManager.GetString("TheHeadOfTheOrganizationInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are 2 main roles in an organization: a team leader and a team member. Unlike a member, a team leader can invite and remove users, as well as manage the plan..
        /// </summary>
        public static string ThereMainRolesOrganization {
            get {
                return ResourceManager.GetString("ThereMainRolesOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are 2 main roles in the team. Project manager (assigned to a project) and other members. The project manager can edit tasks and manage the tasks of others, as well as grant similar rights to other members..
        /// </summary>
        public static string ThereMainRolesTeam {
            get {
                return ResourceManager.GetString("ThereMainRolesTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system operates in a closed format, and to receive an invitation to use the service, .
        /// </summary>
        public static string TheSystemOperatesClosedFormat {
            get {
                return ResourceManager.GetString("TheSystemOperatesClosedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task performer can indicate the time spent in 2 formats: either add the time spent on the Kanban board or indicate the total number of hours when viewing the task in detail..
        /// </summary>
        public static string TheTaskPerformerIndicate {
            get {
                return ResourceManager.GetString("TheTaskPerformerIndicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The team leader changes/project manager changes. How and where to set up these changes in your account.
        /// </summary>
        public static string TheTeamLeaderChanges {
            get {
                return ResourceManager.GetString("TheTeamLeaderChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is currently not available..
        /// </summary>
        public static string ThisOptionCurrentlyNotAvailable {
            get {
                return ResourceManager.GetString("ThisOptionCurrentlyNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the Project manager, click the Edit button on the Project tab, after which you can change the Project manager. However, at the moment, it is not possible to automatically change the head of the organization..
        /// </summary>
        public static string ToChangeProjectManager {
            get {
                return ResourceManager.GetString("ToChangeProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have shared some of the most frequently asked questions to help you out.
        /// </summary>
        public static string WeHaveSharedSomeMostFrequently {
            get {
                return ResourceManager.GetString("WeHaveSharedSomeMostFrequently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We want to make the service as convenient as possible for you, so you have the opportunity to influence our development. These are requests to implement or improve the functions of our service. They are absolutely free. You can suggest new functionality or improve the current one, and we will process your request and give you feedback..
        /// </summary>
        public static string WeWantMakeServiceConvenient {
            get {
                return ResourceManager.GetString("WeWantMakeServiceConvenient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the requests in the tariff plan.
        /// </summary>
        public static string WhatAreTheRequestsTariffPlan {
            get {
                return ResourceManager.GetString("WhatAreTheRequestsTariffPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the difference between deleting a user and blocking access.
        /// </summary>
        public static string WhatDifferenceBetweenDeleting {
            get {
                return ResourceManager.GetString("WhatDifferenceBetweenDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happens if I cancel my subscription to a paid plan.
        /// </summary>
        public static string WhatHappensCancelSubscription {
            get {
                return ResourceManager.GetString("WhatHappensCancelSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should I do if I lost access to the mail to which my account is linked.
        /// </summary>
        public static string WhatShouldlostAccess {
            get {
                return ResourceManager.GetString("WhatShouldlostAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where can I track the status of my requests.
        /// </summary>
        public static string WhereCanTrackStatusRequests {
            get {
                return ResourceManager.GetString("WhereCanTrackStatusRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, you can switch to another plan at any time through your organization&apos;s settings..
        /// </summary>
        public static string YesYouCanSwitchPlan {
            get {
                return ResourceManager.GetString("YesYouCanSwitchPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can contact us anytime regarding any queries or deals,dont hesitate to clear your doubts before trying our product..
        /// </summary>
        public static string YouCanContactAnytime {
            get {
                return ResourceManager.GetString("YouCanContactAnytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use Google/Microsoft email or another provider to register, but you cannot log in through your account/profile.
        /// </summary>
        public static string YouCanUseGoogleOrMicrosoftEmail {
            get {
                return ResourceManager.GetString("YouCanUseGoogleOrMicrosoftEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the opportunity to send requests/suggestions regarding the functionality of the application that you would like to have..
        /// </summary>
        public static string YouHaveOpportunitySendRequests {
            get {
                return ResourceManager.GetString("YouHaveOpportunitySendRequests", resourceCulture);
            }
        }
    }
}
