<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>284def4e-39fc-40b8-8972-9dce75fe3bd6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DbContexts\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js.map" />
    <None Include="wwwroot\lib\bootstrap\LICENSE" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Google.Apis" Version="1.69.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.69.0.3742" />
    <PackageReference Include="IdentityModel" Version="7.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="9.0.4" />
    <PackageReference Include="MimeKit" Version="4.11.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ReverseMarkdown" Version="4.7.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.24.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
    <Folder Include="Services\Telegram\TelegramTicketGenerator\" />
    <Folder Include="wwwroot\lib\chart.js\docs\" />
    <Folder Include="wwwroot\lib\choices.js\src\" />
    <Folder Include="wwwroot\lib\datatables.net-bs5\types\" />
    <Folder Include="wwwroot\lib\flatpickr\types\" />
    <Folder Include="wwwroot\lib\flatpickr\utils\" />
    <Folder Include="wwwroot\lib\gmaps\docs\" />
    <Folder Include="wwwroot\lib\gmaps\examples\" />
    <Folder Include="wwwroot\lib\gmaps\test\" />
    <Folder Include="wwwroot\lib\gridjs\src\" />
    <Folder Include="wwwroot\lib\particles.js\demo\" />
    <Folder Include="wwwroot\lib\rater-js\example\" />
    <Folder Include="wwwroot\lib\rater-js\test\" />
    <Folder Include="wwwroot\lib\swiper\angular\angular\src\" />
    <Folder Include="wwwroot\lib\swiper\angular\esm2020\angular\src\" />
    <Folder Include="wwwroot\lib\swiper\types\modules\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data\Data.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\ErrorResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\LandingResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LandingResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SharedResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharedResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Update="DbContexts\launchSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\ErrorResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorResources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>ByteBusters.Web.Resources</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ErrorResources.uk.resx">
      <CustomToolNamespace>ByteBusters.Web.Resources</CustomToolNamespace>
    </EmbeddedResource>

    <EmbeddedResource Update="Resources\SharedResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SharedResources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>ByteBusters.Web.Resources</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SharedResources.uk.resx">
      <CustomToolNamespace>ByteBusters.Web.Resources</CustomToolNamespace>
    </EmbeddedResource>

    <EmbeddedResource Update="Resources\LandingResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>LandingResources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>ByteBusters.Web.Resources</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\LandingResources.uk.resx">
      <CustomToolNamespace>ByteBusters.Web.Resources</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

</Project>
